// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonManagement.Infrastructure.Data;

#nullable disable

namespace PersonManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonManagement.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAddress")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdAddress")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Alice Silva"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1985, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Name = "Bruno Costa"
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1995, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a3000000-0000-0000-0000-000000000003"),
                            Name = "Carla Mendes"
                        },
                        new
                        {
                            Id = new Guid("b4000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1988, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a4000000-0000-0000-0000-000000000004"),
                            Name = "Diego Ferreira"
                        },
                        new
                        {
                            Id = new Guid("b5000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(1993, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a5000000-0000-0000-0000-000000000005"),
                            Name = "Elena Rocha"
                        },
                        new
                        {
                            Id = new Guid("b6000000-0000-0000-0000-000000000006"),
                            DateOfBirth = new DateTime(1982, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a6000000-0000-0000-0000-000000000006"),
                            Name = "Felipe Andrade"
                        },
                        new
                        {
                            Id = new Guid("b7000000-0000-0000-0000-000000000007"),
                            DateOfBirth = new DateTime(1997, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a7000000-0000-0000-0000-000000000007"),
                            Name = "Gabriela Lima"
                        },
                        new
                        {
                            Id = new Guid("b8000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1991, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a8000000-0000-0000-0000-000000000008"),
                            Name = "Henrique Souza"
                        },
                        new
                        {
                            Id = new Guid("b9000000-0000-0000-0000-000000000009"),
                            DateOfBirth = new DateTime(1999, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("a9000000-0000-0000-0000-000000000009"),
                            Name = "Isabela Martins"
                        },
                        new
                        {
                            Id = new Guid("ba000000-0000-0000-0000-00000000000a"),
                            DateOfBirth = new DateTime(1980, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("aa000000-0000-0000-0000-00000000000a"),
                            Name = "João Pereira"
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-00000000000b"),
                            DateOfBirth = new DateTime(1994, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("ab000000-0000-0000-0000-00000000000b"),
                            Name = "Karen Nascimento"
                        },
                        new
                        {
                            Id = new Guid("bc000000-0000-0000-0000-00000000000c"),
                            DateOfBirth = new DateTime(1987, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("ac000000-0000-0000-0000-00000000000c"),
                            Name = "Lucas Oliveira"
                        },
                        new
                        {
                            Id = new Guid("bd000000-0000-0000-0000-00000000000d"),
                            DateOfBirth = new DateTime(1996, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("ad000000-0000-0000-0000-00000000000d"),
                            Name = "Mariana Castro"
                        },
                        new
                        {
                            Id = new Guid("be000000-0000-0000-0000-00000000000e"),
                            DateOfBirth = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("ae000000-0000-0000-0000-00000000000e"),
                            Name = "Nicolas Barbosa"
                        },
                        new
                        {
                            Id = new Guid("bf000000-0000-0000-0000-00000000000f"),
                            DateOfBirth = new DateTime(1989, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAddress = new Guid("af000000-0000-0000-0000-00000000000f"),
                            Name = "Olivia Cardoso"
                        });
                });

            modelBuilder.Entity("PersonManagement.Domain.Entities.PersonAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("PersonAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            City = "São Paulo",
                            Country = "BR",
                            Neighborhood = "Jardins",
                            Number = "100",
                            State = "SP",
                            Street = "Rua das Flores"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000002"),
                            City = "Rio de Janeiro",
                            Complement = "Apto 10",
                            Country = "BR",
                            Neighborhood = "Copacabana",
                            Number = "200",
                            State = "RJ",
                            Street = "Av. Atlântica"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-0000-0000-000000000003"),
                            City = "Curitiba",
                            Country = "BR",
                            Neighborhood = "Centro",
                            Number = "300",
                            State = "PR",
                            Street = "Rua XV de Novembro"
                        },
                        new
                        {
                            Id = new Guid("a4000000-0000-0000-0000-000000000004"),
                            City = "São Paulo",
                            Complement = "Cj 42",
                            Country = "BR",
                            Neighborhood = "Bela Vista",
                            Number = "1500",
                            State = "SP",
                            Street = "Av. Paulista"
                        },
                        new
                        {
                            Id = new Guid("a5000000-0000-0000-0000-000000000005"),
                            City = "Belo Horizonte",
                            Country = "BR",
                            Neighborhood = "Savassi",
                            Number = "88",
                            State = "MG",
                            Street = "Rua da Liberdade"
                        },
                        new
                        {
                            Id = new Guid("a6000000-0000-0000-0000-000000000006"),
                            City = "Salvador",
                            Country = "BR",
                            Neighborhood = "Centro",
                            Number = "45",
                            State = "BA",
                            Street = "Rua Sete de Setembro"
                        },
                        new
                        {
                            Id = new Guid("a7000000-0000-0000-0000-000000000007"),
                            City = "Fortaleza",
                            Complement = "Sala 3",
                            Country = "BR",
                            Neighborhood = "Aldeota",
                            Number = "210",
                            State = "CE",
                            Street = "Rua do Comércio"
                        },
                        new
                        {
                            Id = new Guid("a8000000-0000-0000-0000-000000000008"),
                            City = "Manaus",
                            Country = "BR",
                            Neighborhood = "Centro",
                            Number = "900",
                            State = "AM",
                            Street = "Av. Brasil"
                        },
                        new
                        {
                            Id = new Guid("a9000000-0000-0000-0000-000000000009"),
                            City = "Porto Alegre",
                            Country = "BR",
                            Neighborhood = "Moinhos de Vento",
                            Number = "55",
                            State = "RS",
                            Street = "Rua das Palmeiras"
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-00000000000a"),
                            City = "Belém",
                            Country = "BR",
                            Neighborhood = "Nazaré",
                            Number = "320",
                            State = "PA",
                            Street = "Av. Amazonas"
                        },
                        new
                        {
                            Id = new Guid("ab000000-0000-0000-0000-00000000000b"),
                            City = "Recife",
                            Complement = "Apto 2",
                            Country = "BR",
                            Neighborhood = "Boa Vista",
                            Number = "77",
                            State = "PE",
                            Street = "Rua Marechal Deodoro"
                        },
                        new
                        {
                            Id = new Guid("ac000000-0000-0000-0000-00000000000c"),
                            City = "Goiânia",
                            Country = "BR",
                            Neighborhood = "Setor Bueno",
                            Number = "14",
                            State = "GO",
                            Street = "Rua das Acácias"
                        },
                        new
                        {
                            Id = new Guid("ad000000-0000-0000-0000-00000000000d"),
                            City = "Florianópolis",
                            Country = "BR",
                            Neighborhood = "Centro",
                            Number = "500",
                            State = "SC",
                            Street = "Rua da Praia"
                        },
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-00000000000e"),
                            City = "Brasília",
                            Complement = "Bl. B",
                            Country = "BR",
                            Neighborhood = "Asa Sul",
                            Number = "730",
                            State = "DF",
                            Street = "Av. das Nações"
                        },
                        new
                        {
                            Id = new Guid("af000000-0000-0000-0000-00000000000f"),
                            City = "Natal",
                            Country = "BR",
                            Neighborhood = "Petrópolis",
                            Number = "62",
                            State = "RN",
                            Street = "Rua Tiradentes"
                        });
                });

            modelBuilder.Entity("PersonManagement.Domain.Entities.Person", b =>
                {
                    b.HasOne("PersonManagement.Domain.Entities.PersonAddress", "Address")
                        .WithOne()
                        .HasForeignKey("PersonManagement.Domain.Entities.Person", "IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
